// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvaqRyF5YHg3BmxdcpVJQNyIaKeXzXDI',
    appId: '1:836786636034:web:20d17fc52837680bde6e1b',
    messagingSenderId: '836786636034',
    projectId: 'sleepmonitor-41f08',
    authDomain: 'sleepmonitor-41f08.firebaseapp.com',
    storageBucket: 'sleepmonitor-41f08.firebasestorage.app',
    measurementId: 'G-QDTP7BM72P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMiVMUO_5vL7d5VKv_kmX-LjmNaWfss4',
    appId: '1:836786636034:android:11d450998216c916de6e1b',
    messagingSenderId: '836786636034',
    projectId: 'sleepmonitor-41f08',
    storageBucket: 'sleepmonitor-41f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXgLxWDOWiywE5yhhGt0yzHttljfbKBo',
    appId: '1:836786636034:ios:3e253fc3fe2d3f56de6e1b',
    messagingSenderId: '836786636034',
    projectId: 'sleepmonitor-41f08',
    storageBucket: 'sleepmonitor-41f08.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXgLxWDOWiywE5yhhGt0yzHttljfbKBo',
    appId: '1:836786636034:ios:3e253fc3fe2d3f56de6e1b',
    messagingSenderId: '836786636034',
    projectId: 'sleepmonitor-41f08',
    storageBucket: 'sleepmonitor-41f08.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvaqRyF5YHg3BmxdcpVJQNyIaKeXzXDI',
    appId: '1:836786636034:web:2b61592c84fbaafede6e1b',
    messagingSenderId: '836786636034',
    projectId: 'sleepmonitor-41f08',
    authDomain: 'sleepmonitor-41f08.firebaseapp.com',
    storageBucket: 'sleepmonitor-41f08.firebasestorage.app',
    measurementId: 'G-X99DYXR7W6',
  );
}
