import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_app/pages/authentication/AuthWrapper.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`
import 'package:flutter_app/pages/app_theme.dart';
import 'package:flutter_app/navigation/main_navigation_wrapper.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SleepMonitorApp());
}

class SleepMonitorApp extends StatelessWidget {
  const SleepMonitorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Sleep Monitor',
      theme: AppTheme.darkTheme,
      home: const AuthWrapper(),
    );
  }
}
